### ISSUE TITLE
Datetime with timezone info serialization

### ISSUE THREAD

**Issue by adarshk7** [kvesteri/serializer#1]
Consider such a case:

```
class Something(db.Model, Serializable):
    ...
    @property
    def something_time_local(self):
         # Returns datetime with tzinfo
         ...
    ...
    def attributes(self):
        return set([..., 'something_time_local', ...])
```

It would be nice to have `something_time_local` attribute in the JSON with time zone info.

Right now it gets converted to  `'2077-06-12T15:30:00.000Z'`, even when the datetime has tzinfo, but it could be useful if it were like `'2077-06-12T15:30:00+02:00'`, in case there is a tzinfo associated with the datetime object. For my case I had to make sure to call to `datetime_obj.isoformat()` in another property and use that in the attribute.

**Comment by kvesteri** [comment]
Please use marshmallow instead of serializer: http://marshmallow.readthedocs.org/en/latest/

**Comment by adarshk7** [comment]
Thanks!
